-- Fix member names corrupted by the original import (importMembers.mjs).
-- Root cause: the import's hand-rolled xlsx reader dropped shared strings
-- containing line breaks (126 of them), shifting every later string index by
-- one. Result: for the second half of the sheet each account got the NEXT
-- member's name, and 30 emails were skipped entirely.
-- This migration corrects names from the authoritative (name, email) pairs in
-- "AUSS 2026 Members.xlsx" and creates the 30 missing accounts. It touches
-- ONLY the affected rows: no passwords, tokens, consent rows or other data are
-- rewritten (members who reset their passwords keep them).

-- 1) Correct the 214 wrong names (upsert so it also covers any missing UserInfo row).
INSERT INTO "UserInfo" ("id", "userId", "firstName", "lastName")
SELECT gen_random_uuid(), u."id", v."firstName", v."lastName"
FROM (VALUES
  ($str$aerielmatthew@gmail.com$str$, $str$Aeriel$str$, $str$Cruz$str$),
  ($str$slin464@aucklanduni.ac.nz$str$, $str$Selwyn$str$, $str$Lin$str$),
  ($str$chsean0615@gmail.com$str$, $str$Sean$str$, $str$Chun$str$),
  ($str$wayneshen2007@gmail.com$str$, $str$Wayne$str$, $str$Shen$str$),
  ($str$jhaj589@aucklanduni.ac.nz$str$, $str$Jaas Haja$str$, $str$Hussain$str$),
  ($str$ghar611@aucklanduni.ac.nz$str$, $str$Gypsy$str$, $str$Harvey$str$),
  ($str$hxh6151@autuni.ac.nz$str$, $str$Philip$str$, $str$Gee$str$),
  ($str$sout925@aucklanduni.ac.nz$str$, $str$Sorya$str$, $str$Out$str$),
  ($str$jimmyhenshaw807@gmail.com$str$, $str$James$str$, $str$Henshaw$str$),
  ($str$dnail.chirackal@gmail.com$str$, $str$Danil$str$, $str$Chirackal$str$),
  ($str$amhk209@aucklanduni.ac.nz$str$, $str$Adil$str$, $str$Khan$str$),
  ($str$awoo990@aucklanduni.ac$str$, $str$Amelie$str$, $str$Wood$str$),
  ($str$jqui742@aucklanduni.ac.nz$str$, $str$Jefinjan$str$, $str$Quiambao$str$),
  ($str$ncoe227@aucklanduni.ac.nz$str$, $str$Nicholas$str$, $str$Coetzee$str$),
  ($str$ohes671@aucklanduni.ac.nz$str$, $str$Omid$str$, $str$Hesari$str$),
  ($str$mpar591@auckalduni.ac.nz$str$, $str$Minjae$str$, $str$Park$str$),
  ($str$aman928@aucklanduni.ac.nz$str$, $str$Abi$str$, $str$Manayil$str$),
  ($str$adau506@aucklanduni.ac.nz$str$, $str$Alexandre$str$, $str$Dault$str$),
  ($str$hayleychin7@gmail.com$str$, $str$Hayley$str$, $str$Chin$str$),
  ($str$jsun309@aucklanduni.ac.nz$str$, $str$Cic$str$, $str$Sun$str$),
  ($str$ngu.jess06@gmail.com$str$, $str$Jessica$str$, $str$Nguyen$str$),
  ($str$klay147@aucklanduni.ac.nz$str$, $str$Karl$str$, $str$Laylo$str$),
  ($str$acam586@aucklanduni.ac.nz$str$, $str$Apollo$str$, $str$Cameron-Boot$str$),
  ($str$fmca216@aucklanduni.ac.nz$str$, $str$Felix$str$, $str$McAuley$str$),
  ($str$yaha919@aucklanduni.ac.nz$str$, $str$Yinon$str$, $str$Aharony$str$),
  ($str$dlev499@aucklanduni.ac.nz$str$, $str$Dani$str$, $str$Levy$str$),
  ($str$ria.khurana@icloud.com$str$, $str$Ria$str$, $str$Khurana$str$),
  ($str$jsim415@aucklanduni.ac.nz$str$, $str$Jia Xin$str$, $str$Sim$str$),
  ($str$nyan129@aucklanduni.ac.nz$str$, $str$Nick$str$, $str$Yang$str$),
  ($str$atea883@gmail.com$str$, $str$Adrian$str$, $str$Tea$str$),
  ($str$awwe465@aucklanduni.ac.nz$str$, $str$Anuk$str$, $str$Weerasinghe$str$),
  ($str$rstr721@aucklanduni.ac.nz$str$, $str$Ruby$str$, $str$Stretch-Treweek$str$),
  ($str$imamurakoki004@gmail.com$str$, $str$Koki$str$, $str$Imamura$str$),
  ($str$xsny378@aucklanduni.ac.nz$str$, $str$Xander$str$, $str$Snyman$str$),
  ($str$slar651@aucklanduni.ac.nz$str$, $str$Soz$str$, $str$Larsen$str$),
  ($str$jmcl857@aucklanduni.ac.nz$str$, $str$Jack$str$, $str$Mclachlan$str$),
  ($str$ntal505@aucklanduni.ac.nz$str$, $str$Nargiss$str$, $str$Taleb$str$),
  ($str$sles809@aucklanduni.ac.nz$str$, $str$Shaun$str$, $str$Leslie$str$),
  ($str$wlow138@aucklanduni.ac.nz$str$, $str$Liv WM$str$, $str$Low$str$),
  ($str$cric505@aucklanduni.ac.nz$str$, $str$Christian$str$, $str$Richliev$str$),
  ($str$hlai112@aucklanduni.ac.nz$str$, $str$Henry$str$, $str$Lai$str$),
  ($str$srow898@aucklanduni.ac.nz$str$, $str$Summer$str$, $str$Rowsell$str$),
  ($str$kkri178@aucklanduni.ac.nz$str$, $str$kush$str$, $str$krishna$str$),
  ($str$jimm269@aucklanduni.ac.nz$str$, $str$James$str$, $str$Immanuel$str$),
  ($str$lin.bobby123@gmail.com$str$, $str$Bobby$str$, $str$Lin$str$),
  ($str$kwal133@aucklanduni.ac.nz$str$, $str$Kate$str$, $str$Walker$str$),
  ($str$adun475@aucklanduni.ac.nz$str$, $str$Amelia$str$, $str$Dunbar$str$),
  ($str$vten138@aucklanduni.ac.nz$str$, $str$Victoria$str$, $str$Tenitskaya$str$),
  ($str$rmat631@aucklanduni.ac.nz$str$, $str$Raunaq$str$, $str$Matharu$str$),
  ($str$rdn7015@autuni.ac.nz$str$, $str$gian$str$, $str$Mijares$str$),
  ($str$thug066@aucklanduni.ac.nz$str$, $str$Tobey$str$, $str$Hughes$str$),
  ($str$jbin902@aucklanduni.ac.nz$str$, $str$Jaimee$str$, $str$Bingley$str$),
  ($str$leonep0914@gmail.com$str$, $str$Leone$str$, $str$Paialii$str$),
  ($str$hsha351@aucklanduni.ac.nz$str$, $str$Harikesh$str$, $str$Shanker$str$),
  ($str$bane589@aucklanduni.ac.nz$str$, $str$Bhuwan$str$, $str$Aneja$str$),
  ($str$llin934@aucklanduni.ac.nz$str$, $str$Lino$str$, $str$Lino$str$),
  ($str$amit853@aucklanduni.ac.nz$str$, $str$Angad$str$, $str$Mittal$str$),
  ($str$araj306@aucklnaduni.ac.nz$str$, $str$Aswin$str$, $str$Raj$str$),
  ($str$fran091@aucklanduni.ac.nz$str$, $str$Felix$str$, $str$Randle$str$),
  ($str$adom941@auckland.ac.nz$str$, $str$Radj$str$, $str$Domingo$str$),
  ($str$awoo908@aucklanduni.ac.nz$str$, $str$Andrey$str$, $str$Woodside$str$),
  ($str$trad603@aucklanduni.ac.nz$str$, $str$thusmirthan$str$, $str$radhakrishnan$str$),
  ($str$kironpeng@gmail.com$str$, $str$Kiron$str$, $str$Peng$str$),
  ($str$wangruiqiao7@gmail.com$str$, $str$Ruiqiao$str$, $str$Wang$str$),
  ($str$haoqianliu633@gmail.com$str$, $str$Haoqian$str$, $str$Liu$str$),
  ($str$lcho603@aucklanduni.ac.nz$str$, $str$Leighton$str$, $str$Choeung$str$),
  ($str$asus686@aucklanduni.ac.nz$str$, $str$Aidan$str$, $str$Susanto$str$),
  ($str$duonggiabao.le0203@gmail.com$str$, $str$Brian$str$, $str$Le$str$),
  ($str$afridmohammed0722@hotmail.com$str$, $str$Afrid$str$, $str$Hussain$str$),
  ($str$yanhmueaung@gmail.com$str$, $str$Yan Hmue$str$, $str$Aung$str$),
  ($str$kaeastewart@gmail.com$str$, $str$Ryan$str$, $str$Stevsn$str$),
  ($str$mcdonaldluke10@gmail.com$str$, $str$Luke$str$, $str$McDonald$str$),
  ($str$jcor606@aucklanduni.ac.nz$str$, $str$Jose$str$, $str$Corsame$str$),
  ($str$jrc1110@autuni.ac.nz$str$, $str$Carlos$str$, $str$Roldan$str$),
  ($str$yhp0180@autuni.school.nz$str$, $str$Iggi$str$, $str$Gervacio$str$),
  ($str$scon395@auckland.ac.nz$str$, $str$Sami$str$, $str$Conrad$str$),
  ($str$npat374@aucklanduni.ac.nz$str$, $str$Nishali$str$, $str$Patel$str$),
  ($str$ntah765@aucklanduni.ac.nz$str$, $str$Pranuja$str$, $str$Tahal$str$),
  ($str$swwe386@aucklanduni.ac.nz$str$, $str$Seshan$str$, $str$Weeraratne$str$),
  ($str$lund345@aucklanduni.ac.nz$str$, $str$Libby$str$, $str$Underwood$str$),
  ($str$elee476@aucklanduni.ac.nz$str$, $str$Elliot$str$, $str$Lee$str$),
  ($str$fwat215@aucklanduni.ac.nz$str$, $str$Fletcher$str$, $str$Watts$str$),
  ($str$rong789@aucklanduni.ac.nz$str$, $str$Regan$str$, $str$Ong$str$),
  ($str$ypat499@aucklanduni.ac.nz$str$, $str$Yachna$str$, $str$Patel$str$),
  ($str$aant42@auckland.ac.nz$str$, $str$Alan$str$, $str$Antony$str$),
  ($str$amano.taich@gmail.com$str$, $str$Taichi$str$, $str$Amano$str$),
  ($str$jpor151@aucklanduni.ac.nz$str$, $str$Jacob$str$, $str$Porter$str$),
  ($str$antonyreveley@gmail.com$str$, $str$antony$str$, $str$reveley$str$),
  ($str$lakindubalasoorya@gmail.com$str$, $str$Lakindu$str$, $str$Balasooriya$str$),
  ($str$aria.l4jackson@gmail.com$str$, $str$Te Aria$str$, $str$Jackson$str$),
  ($str$apen955@aucklanduni.ac.nz$str$, $str$Alex$str$, $str$Pengelly$str$),
  ($str$tommytrinhnznz@gmail.com$str$, $str$Tommy$str$, $str$Trinh$str$),
  ($str$fcun012@aucklanduni.ac.nz$str$, $str$Flynn$str$, $str$Cunningham-Beentjes$str$),
  ($str$jnic854@aucklanduni.ac.nz$str$, $str$Jake$str$, $str$Nicholas$str$),
  ($str$llig239@aucklanduni.ac.nz$str$, $str$Luca$str$, $str$Liggins$str$),
  ($str$tom.fogarty@auckland.ac.nz$str$, $str$Tom$str$, $str$Fogarty$str$),
  ($str$dbin022@aucklanduni.ac.nz$str$, $str$Darren$str$, $str$Binsol$str$),
  ($str$esun219@aucklanduni.ac.nz$str$, $str$Ethan$str$, $str$Sun$str$),
  ($str$janeguiguit@gmail.com$str$, $str$Jane$str$, $str$GUIGUIT$str$),
  ($str$brunohannaford538@gmail.com$str$, $str$Bruno$str$, $str$Hannaford$str$),
  ($str$mkim824@aucklanduni.ac.nz$str$, $str$Jay$str$, $str$Kim$str$),
  ($str$nagrom6789@gmail.com$str$, $str$Morgan$str$, $str$Thompson$str$),
  ($str$atho327@aucklanduni.ac.nz$str$, $str$Alex$str$, $str$Thorpe$str$),
  ($str$csol828@aucklanduni.ac.nz$str$, $str$Christian$str$, $str$Solomon$str$),
  ($str$wyim433@aucklanduni.ac.nz$str$, $str$Wu Xin$str$, $str$Yim$str$),
  ($str$lmou382@aucklanduni.ac.nz$str$, $str$Lana$str$, $str$Mourad$str$),
  ($str$thorbridgerr@gmail.com$str$, $str$Thor$str$, $str$Bridger$str$),
  ($str$aahk783@aucklanduni.ac.nz$str$, $str$Adam$str$, $str$Khalil$str$),
  ($str$jwu769@aucklanduni.ac.nz$str$, $str$James$str$, $str$Wu$str$),
  ($str$lhar318@aucklanduni.ac.nz$str$, $str$Liam$str$, $str$Harvey$str$),
  ($str$amar853@aucklanduni.ac.nz$str$, $str$Arham$str$, $str$Marzook$str$),
  ($str$gren464@aucklanduni.ac.nz$str$, $str$Grace$str$, $str$Rennie$str$),
  ($str$ragn997@aucklanduni.ac.nz$str$, $str$Rithwik$str$, $str$Agnihotri$str$),
  ($str$rtur509@aucklanduni.ac.nz$str$, $str$Ryan$str$, $str$Turley$str$),
  ($str$18684821852@163.com$str$, $str$Wen$str$, $str$Yin$str$),
  ($str$rcxthh@163.com$str$, $str$chenyi$str$, $str$gao$str$),
  ($str$rgra572@aucklanduni.ac.nz$str$, $str$Rhett$str$, $str$Graham$str$),
  ($str$melaniesands@gmail.com$str$, $str$Melanie$str$, $str$Sands$str$),
  ($str$zsu940@aucklanduni.ac.nz$str$, $str$Zhi Pei$str$, $str$Su$str$),
  ($str$lliu195@aucklanduni.ac.nz$str$, $str$Leo$str$, $str$Liu$str$),
  ($str$zals918@aucklanduni.ac.nz$str$, $str$Zaid$str$, $str$Al-Sakini$str$),
  ($str$mwhe184@aucklanduni.ac.nz$str$, $str$Michael$str$, $str$Wheeler$str$),
  ($str$jmcg829@aucklanduni.ac.nz$str$, $str$Josef$str$, $str$McGrath$str$),
  ($str$yinuo345@gmail.com$str$, $str$Enoch$str$, $str$Jiang$str$),
  ($str$kma640@aucklanduni.ac.nz$str$, $str$Mickey$str$, $str$Ma$str$),
  ($str$xsim733@auckland.ac.nz$str$, $str$Xavier$str$, $str$Simpkins$str$),
  ($str$jcho597@aucklanduni.ac.nz$str$, $str$Jeongwoon$str$, $str$Choi$str$),
  ($str$csai300@aucklanduni.ac.nz$str$, $str$Chris$str$, $str$Sainty$str$),
  ($str$llaw553@aucklanduni.ac.nz$str$, $str$Luca$str$, $str$Lawson$str$),
  ($str$inar984@aucklanduni.ac.nz$str$, $str$Indu$str$, $str$Narahenpitage$str$),
  ($str$0226jessiewong@gmail.com$str$, $str$Jessie$str$, $str$Wong$str$),
  ($str$braydenp114@gmail.com$str$, $str$Brayden$str$, $str$Pearce$str$),
  ($str$pwir090@aucklanduni.ac.nz$str$, $str$Paora$str$, $str$Wi-Repa$str$),
  ($str$tmcl763@aucklanduni.ac.nz$str$, $str$Tessa$str$, $str$McLaren$str$),
  ($str$jsta781@aucklanduni.ac.nz$str$, $str$Jack$str$, $str$Stansfield$str$),
  ($str$jcla240@aucklanduni.ac.nz$str$, $str$Jakob$str$, $str$Clapham$str$),
  ($str$kwat522@aucklanduni.ac.nz$str$, $str$Katherine$str$, $str$Watts$str$),
  ($str$arob590@aucklanduni.ac.nz$str$, $str$Artemisia$str$, $str$Robillon$str$),
  ($str$ttec863@aucklanduni.ac.nz$str$, $str$TJ$str$, $str$Tecson$str$),
  ($str$dbin270@aucklanduni.ac.nz$str$, $str$Dane$str$, $str$Binsol$str$),
  ($str$ckwo934@aucklanduni.ac.nz$str$, $str$Caelan$str$, $str$Kwok$str$),
  ($str$arjunvadiyar14@gmail.com$str$, $str$Arjun$str$, $str$Vadiyar$str$),
  ($str$gsho948@aucklanduni.ac.nz$str$, $str$Garry$str$, $str$Shoker$str$),
  ($str$huhaonan999@qq.com$str$, $str$Haonan$str$, $str$Hu$str$),
  ($str$lgui948@aucklanduni.ac.nz$str$, $str$Leah$str$, $str$Guico$str$),
  ($str$anthonyhsieh189@gmail.com$str$, $str$Anthony$str$, $str$Hsieh$str$),
  ($str$hbis025@aucklanduni.ac.nz$str$, $str$Hunter$str$, $str$Bishop$str$),
  ($str$mcha916@aucklanduni.ac.nz$str$, $str$Matthew$str$, $str$Chandler$str$),
  ($str$ctib485@aucklanduni.ac.nz$str$, $str$Curtis$str$, $str$Tibbles$str$),
  ($str$mpar591@aucklanduni.ac.nz$str$, $str$Minjae$str$, $str$Park$str$),
  ($str$amam862@aucklanduni.ac.nz$str$, $str$Audrie$str$, $str$Mamaradlo$str$),
  ($str$zgb0408@autuni.ac.nz$str$, $str$Angelo$str$, $str$Tienzo$str$),
  ($str$slin585@aucklanduni.ac.nz$str$, $str$Ivan$str$, $str$Lin$str$),
  ($str$jmir662@auckland.ac.nz$str$, $str$John$str$, $str$Razon$str$),
  ($str$pxu163@aucklanduni.ac.nz$str$, $str$Paco$str$, $str$Xu$str$),
  ($str$brag429@aucklanduni.ac.nz$str$, $str$Balamurali$str$, $str$Ragupathi$str$),
  ($str$jaydenphamofficial@gmail.com$str$, $str$Jayden$str$, $str$Pham$str$),
  ($str$calvin.dysart@mds.ac.nz$str$, $str$Calvin$str$, $str$Dysart$str$),
  ($str$teva029@aucklanduni.ac.nz$str$, $str$Tane$str$, $str$Evans-Clarke$str$),
  ($str$hlee826@aucklanduni.ac.nz$str$, $str$Simon$str$, $str$Lee$str$),
  ($str$aadq24we@gmail.com$str$, $str$yijun$str$, $str$liu$str$),
  ($str$bwat245@aucklanduni.ac.nz$str$, $str$Benjamin$str$, $str$Watson$str$),
  ($str$hvan524@aucklanduni.ac.nz$str$, $str$Hugo Van Der$str$, $str$Maas$str$),
  ($str$sedd712@aucklanduni.ac.nz$str$, $str$Sophie$str$, $str$Eddington$str$),
  ($str$zhaf021@aucklanduni.ac.nz$str$, $str$Zakaria$str$, $str$Hafeez$str$),
  ($str$smur809@aucklanduni.ac.nz$str$, $str$Hari$str$, $str$Muralidaran$str$),
  ($str$rdev395@aucklanduni.ac.nz$str$, $str$Renesh$str$, $str$Devanand$str$),
  ($str$avya737@aucklanduni.ac.nz$str$, $str$Aman$str$, $str$Vyas$str$),
  ($str$erau548@aucklanduni.ac.nz$str$, $str$Emily$str$, $str$Raukura$str$),
  ($str$agha984@aucklanduni.ac.nz$str$, $str$Ali$str$, $str$Ghadiri$str$),
  ($str$vladxtys@gmail.com$str$, $str$Vlad$str$, $str$Tyshchenko$str$),
  ($str$ptay408@aucklanduni.ac.nz$str$, $str$philip$str$, $str$taylor$str$),
  ($str$richiesingh2008@gmail.com$str$, $str$Richie$str$, $str$Singh$str$),
  ($str$osca399@aucklanduni.ac.nz$str$, $str$Olano$str$, $str$Scarlett$str$),
  ($str$crv8085@aut.ac.nz$str$, $str$Arnav Singh$str$, $str$Sajwan$str$),
  ($str$ccal332@aucklanduni.ac.nz$str$, $str$Charles$str$, $str$Callagher$str$),
  ($str$qhsi807@aucklanduni.ac.nz$str$, $str$Queenie$str$, $str$Hsiung$str$),
  ($str$dcha656@aucklanduni.ac.nz$str$, $str$Dev$str$, $str$Chand$str$),
  ($str$coch535@aucklanduni.ac.nz$str$, $str$Chisom$str$, $str$Ochibulu$str$),
  ($str$rcon898@aucklanduni.ac.nz$str$, $str$Ryan$str$, $str$Cong$str$),
  ($str$liangjupei35@qq.com$str$, $str$Jupei$str$, $str$Liang$str$),
  ($str$3433797405@qq.com$str$, $str$JUPEI$str$, $str$LIANG$str$),
  ($str$pfer048@aucklanduni.ac.nz$str$, $str$Rekshan$str$, $str$Fernando$str$),
  ($str$meyepa5659@diarshop.com$str$, $str$Sem2$str$, $str$Sem2$str$),
  ($str$zhaoyihao0329@gmail.com$str$, $str$Yihao$str$, $str$Zhao$str$),
  ($str$kmat508@aucklanduni.ac.nz$str$, $str$Kevin$str$, $str$Mathew$str$),
  ($str$rche691@aucklanduni.ac.nz$str$, $str$Ray$str$, $str$Chen$str$),
  ($str$tura926@aucklanduni.ac.nz$str$, $str$Tsuyoshi$str$, $str$Uragami$str$),
  ($str$janamwalia@gmail.com$str$, $str$Janam$str$, $str$Walia$str$),
  ($str$togi316@aucklanduni.ac.nz$str$, $str$Tobi$str$, $str$Ogunnoiki$str$),
  ($str$expong8@gmail.com$str$, $str$Josh$str$, $str$Fuller$str$),
  ($str$mpai510@aucklanduni.ac.nz$str$, $str$Maximillian$str$, $str$Paing$str$),
  ($str$scu8ts@gmail.com$str$, $str$Joseph$str$, $str$Faalogo$str$),
  ($str$kste352@aucklanduni.ac.nz$str$, $str$Kai$str$, $str$Steinke$str$),
  ($str$jdeg861@aucklanduni.ac.nz$str$, $str$Josh De$str$, $str$Guzman$str$),
  ($str$tennysonli1982@gmail.com$str$, $str$Tennyson$str$, $str$Li$str$),
  ($str$ltan300@aucklanduni.ac.nz$str$, $str$Lawrence$str$, $str$TN$str$),
  ($str$ateo250@aucklanduni.ac.nz$str$, $str$aiden$str$, $str$teo$str$),
  ($str$rmac450@aucklanduni.ac.nz$str$, $str$Ryoma$str$, $str$MacDonald$str$),
  ($str$olivia357357357@gmail.com$str$, $str$Nuo$str$, $str$Xu$str$),
  ($str$rli934@aucklanduni.ac.nz$str$, $str$Raymond$str$, $str$Li$str$),
  ($str$olock2007@gmail.com$str$, $str$Oliver$str$, $str$Lock$str$),
  ($str$jshi787@aucklanduni.ac.nz$str$, $str$Jaemin$str$, $str$Shin$str$),
  ($str$jzho985@aucklanduni.ac.nz$str$, $str$Jimmy$str$, $str$Zhou$str$),
  ($str$rfun316@aucklanduni.ac.nz$str$, $str$Rei$str$, $str$Fung$str$),
  ($str$jqui742@acuklanduni.ac.nz$str$, $str$Jefinjan$str$, $str$Quiambao$str$),
  ($str$cjoe023@aucklanduni.ac.nz$str$, $str$Christopher$str$, $str$Joeng$str$),
  ($str$zhua276@aucklanduni.ac.nz$str$, $str$Andrew$str$, $str$Huang$str$),
  ($str$emag735@aucklanduni.ac.nz$str$, $str$Ethan$str$, $str$Magpayo$str$),
  ($str$jmck189@aucklanduni.ac.nz$str$, $str$Juliet$str$, $str$Mckenzie$str$),
  ($str$yuanhuiawk@163.com$str$, $str$Hui$str$, $str$Yuan$str$),
  ($str$hxia801@aucklanduni.ac.nz$str$, $str$He$str$, $str$Xiao$str$),
  ($str$ndav413@aucklanduni.ac.nz$str$, $str$Nathan$str$, $str$David$str$),
  ($str$gyv2416@aut.ac.nz$str$, $str$Anthony$str$, $str$Ly$str$)
) AS v("email", "firstName", "lastName")
JOIN "User" u ON u."email" = lower(v."email")
ON CONFLICT ("userId") DO UPDATE SET "firstName" = EXCLUDED."firstName", "lastName" = EXCLUDED."lastName";

-- 2) Create the 30 missing accounts, mirroring importMembers.mjs decisions:
-- USER, isVerified, VERIFIED, consents accepted, random password (member uses
-- forgot-password to set their own).
INSERT INTO "User"
  ("id","email","passwordHash","role","tokenVersion","isVerified","membershipStatus","membershipStatusUpdatedAt","qrVersion",
   "privacyPolicyAcceptedAt","privacyPolicyVersion","membershipAgreementAcceptedAt","membershipAgreementVersion",
   "lastCodeSentAt","verificationExpiresAt","createdAt")
VALUES
  (gen_random_uuid(), $str$jyan178@aucklanduni.ac.nz$str$, $str$$2b$10$X8e61ISLCTfPEXh8bzLxxurzWgR3FDFavb7Qg4ePBwjS9pK246LVS$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$zli499@aucklanduni.ac.nz$str$, $str$$2b$10$TQY3YlAlBYZSquxCAFwTzui0KSEYITIoDSIBJM0Mh4amFtBtXVHY6$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$alexyip5024@gmail.com$str$, $str$$2b$10$8fXOJorvmPbSGFICV14/gOnmLmoz2suuc03XKrIYm1gQxenJZqgnu$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$kdar407@aucklanduni.ac.nz$str$, $str$$2b$10$f3GKkuR3tXgeRFjSZpdeT.rxHcsYiNSqe3bjsUDJjY/TILYorXcRW$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$cdoh674@aucklanduni.ac.nz$str$, $str$$2b$10$k1ILG21ZvAYq7pWwHQ6pkuftgZjimzXtOeWj5VaQK1NiR8kSoaDJ6$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$mloh913@aucklanduni.ac.nz$str$, $str$$2b$10$NOrQtLxznhkNUrxdPHX2d.lGzduznodKgXgtdzVKzjLR1C.YQyZW2$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$acor274@aucklanduni.ac.nz$str$, $str$$2b$10$Z/q5fAtxinhjZvgEkljKPekk.xkb6/vADMEvaBp2QiGxrXtnb0aie$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$eliu545@aucklanduni.ac.nz$str$, $str$$2b$10$vSIvkMZb0JhvvkalCLfu.us2Bw/.PFbQH1I3ImopVjYK6QEGkTVR2$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$worh411@aucklanduni.ac.nz$str$, $str$$2b$10$tjynWJtTPwwQ63sUTwkQEOQz9BJZbumXrZgFdO15uHs1ENA3dk7VG$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$hdra376@aucklanduni.ac.nz$str$, $str$$2b$10$lIzQIrP/t5ICSYai66AMQ.xt.LLmaPI9Q37yH6qLTX3eOPvnfvGH6$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$eteo952@aucklanduni.ac.nz$str$, $str$$2b$10$.53eFqVVDUYi6Ed9YZSasOSVGeUSGeOZs2Q8b0P84PMHXEuKkSBoG$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$aosm640@aucklanduni.ac.nz$str$, $str$$2b$10$7c8IqGMX1ILWhVJyipXrT.BYhVmO8dagjxDfSJj3EqC4pcumNsJ4K$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$fordham.joelle@gmail.com$str$, $str$$2b$10$pOSiWK7hTX/V33/M0aM5/ezjOoxVFcboU73uXpWHQef2CIEFIPMnG$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$tson488@aucklanduni.ac.nz$str$, $str$$2b$10$I3lSadsKJ0i2HGjDP5HKQejsKyQLrNe7mh9bHGOifCcL0ehS6RgSO$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$xesc708@aucklanduni.ac.nz$str$, $str$$2b$10$S87725glLS2TrVitjbhCe.rE6VliR0tEhmK/u8BuQy9LJMppsLn9S$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$scon395@aucklanduni.ac.nz$str$, $str$$2b$10$u4IDLnZogxk5gLqx.30Fou8zgfsekhm7IyrXNVBeTqBDAZwNfVXca$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$xsim733@aucklanduni.ac.nz$str$, $str$$2b$10$ksXh1Dgnfcp6SPzG2xo41u2YAzmS6slXsqkcnmJFPyYa4YGfAOJ/q$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$apon358@aucklanduni.ac.nz$str$, $str$$2b$10$UWRRkp1KOYLqbwYIVW0n9.hP6QG0slt1zBt8mUGoJXdOvuy81xkXu$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$ksb8040@autuni.ac.nz$str$, $str$$2b$10$pQYcK/GmQ6MaMRY3Ud5iMeUw63l22l9GDXn7FlACV9je48Oy.1otq$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$borm820@aucklanduni.ac.nz$str$, $str$$2b$10$tfz0jBqF.MDZ2XH4QWvThOfRVDSSZyr./4iS9bkUvg.uF7oFFcjK.$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$sles473@aucklanduni.ac.nz$str$, $str$$2b$10$t7YHx/s58ae3JXrlT3xn/uCiBe1pUAtbC4oAINLw8F9QdmdWTOTNe$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$apra731@aucklanduni.ac.nz$str$, $str$$2b$10$VScXTqWIRiyFmf3a3xySm.jHTqFSOJ7dMBqZrJFZ2YgjfuTVOQnju$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$fwx4269@autuni.ac.nz$str$, $str$$2b$10$now8sHTHAXzSYwZPjCvDs.IqcFWl3GcAkKZcP/jSj7uc3wBq5fxB2$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$testsem2@gmiasl.com$str$, $str$$2b$10$lokIXnEEA3Lsp0y1PZH9TODqVb9R2RnGSCd08dO.Ldic4m8kZvOR2$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$vman374@aucklanduni.ac.nz$str$, $str$$2b$10$dEo8rYx6q8LcyD9ByWAtEeL01aWKTx4bYWO.awhXopUFzdohqm2ai$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$nman466@aucklanduni.ac.nz$str$, $str$$2b$10$1sxN6wgaQRBpEA8k8Y3ZNuVfpnea3czwAPNpQn2rRIX7qOgx3rxZ.$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$olivia357357@gmail.com$str$, $str$$2b$10$LmufAkYHKXGprnb/Pi.AiOJJ1/prDJP/erkBzqn4YeufWJ0c22Wu2$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$else663@aucklanduni.ac.nz$str$, $str$$2b$10$zX1FHoL6hfKfTJMamKNH8uO/ZOxIzDeh0vrY6arjbOXnHYpjr4e1K$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$asue282@aucklanduni.ac.nz$str$, $str$$2b$10$Tb39xrPITPeVgtRIrG9vL.xwtu7S8S8CyfqfFZBRAl/qddEHXkLHe$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now()),
  (gen_random_uuid(), $str$gwc5014@autuni.ac.nz$str$, $str$$2b$10$9y/WDOUIoVIjB3LVqPFW6OvOXAPzSDf1DTgI5IE4qJMj0OrpFslGS$str$, 'USER', 0, true, 'VERIFIED', now(), 1, now(), '2026-08-18', now(), '2026-08-21', now(), now(), now())
ON CONFLICT ("email") DO NOTHING;

INSERT INTO "UserInfo" ("id", "userId", "firstName", "lastName")
SELECT gen_random_uuid(), u."id", v."firstName", v."lastName"
FROM (VALUES
  ($str$jyan178@aucklanduni.ac.nz$str$, $str$Joe$str$, $str$Yang$str$),
  ($str$zli499@aucklanduni.ac.nz$str$, $str$Leo$str$, $str$Li$str$),
  ($str$alexyip5024@gmail.com$str$, $str$Alex$str$, $str$Yip$str$),
  ($str$kdar407@aucklanduni.ac.nz$str$, $str$Kaitlyn$str$, $str$Darroch$str$),
  ($str$cdoh674@aucklanduni.ac.nz$str$, $str$Carter$str$, $str$Doherty-Parr$str$),
  ($str$mloh913@aucklanduni.ac.nz$str$, $str$Marcus$str$, $str$Loh$str$),
  ($str$acor274@aucklanduni.ac.nz$str$, $str$Adam$str$, $str$Corboy$str$),
  ($str$eliu545@aucklanduni.ac.nz$str$, $str$Ekin$str$, $str$Liu$str$),
  ($str$worh411@aucklanduni.ac.nz$str$, $str$Will$str$, $str$Horne$str$),
  ($str$hdra376@aucklanduni.ac.nz$str$, $str$Hamza$str$, $str$Dragh$str$),
  ($str$eteo952@aucklanduni.ac.nz$str$, $str$Ethan$str$, $str$Teoh$str$),
  ($str$aosm640@aucklanduni.ac.nz$str$, $str$Ahmed$str$, $str$Osman$str$),
  ($str$fordham.joelle@gmail.com$str$, $str$Joey$str$, $str$Fordham$str$),
  ($str$tson488@aucklanduni.ac.nz$str$, $str$Nora$str$, $str$Sone$str$),
  ($str$xesc708@aucklanduni.ac.nz$str$, $str$Xander$str$, $str$Escueta$str$),
  ($str$scon395@aucklanduni.ac.nz$str$, $str$Sami$str$, $str$Conrad$str$),
  ($str$xsim733@aucklanduni.ac.nz$str$, $str$Xavier$str$, $str$Simpkins$str$),
  ($str$apon358@aucklanduni.ac.nz$str$, $str$Aditeya$str$, $str$Ponamanani$str$),
  ($str$ksb8040@autuni.ac.nz$str$, $str$Kris$str$, $str$Lal$str$),
  ($str$borm820@aucklanduni.ac.nz$str$, $str$Baz$str$, $str$Ormond$str$),
  ($str$sles473@aucklanduni.ac.nz$str$, $str$Sean$str$, $str$Lester$str$),
  ($str$apra731@aucklanduni.ac.nz$str$, $str$Ayaan$str$, $str$Prasad$str$),
  ($str$fwx4269@autuni.ac.nz$str$, $str$Hiruka$str$, $str$Abeysooriya$str$),
  ($str$testsem2@gmiasl.com$str$, $str$TestSem2$str$, $str$TestSem2$str$),
  ($str$vman374@aucklanduni.ac.nz$str$, $str$Virgilio$str$, $str$Manaois$str$),
  ($str$nman466@aucklanduni.ac.nz$str$, $str$Nils$str$, $str$Mann$str$),
  ($str$olivia357357@gmail.com$str$, $str$Nuo$str$, $str$Xu$str$),
  ($str$else663@aucklanduni.ac.nz$str$, $str$Sebastian$str$, $str$Lee$str$),
  ($str$asue282@aucklanduni.ac.nz$str$, $str$Amber$str$, $str$Sue$str$),
  ($str$gwc5014@autuni.ac.nz$str$, $str$Alexis$str$, $str$Zhu$str$)
) AS v("email", "firstName", "lastName")
JOIN "User" u ON u."email" = lower(v."email")
ON CONFLICT ("userId") DO NOTHING;
